// <auto-generated />
using System;
using Invoice.Api.Data.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice.Api.Data.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Invoice.Api.Data.Entities.ClientAddressEntity", b =>
                {
                    b.Property<long>("ClientAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClientAddressId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientAddressId"), 1L, 1);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("AddressLine2")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("AddressLine3")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("AddressLine3")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("AddressLine4")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("AddressLine4")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(96)")
                        .HasColumnName("City");

                    b.Property<long>("ClientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClientId");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("NCHAR(2)")
                        .HasColumnName("CountryCode");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BIT")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("BIT")
                        .HasColumnName("IsPrimary");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(8)")
                        .HasColumnName("PostalCode");

                    b.Property<string>("Region")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(96)")
                        .HasColumnName("Region")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("UtcCreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcCreatedDate");

                    b.Property<DateTime?>("UtcDeletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcDeletedDate")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime?>("UtcUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcUpdatedDate")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("ClientAddressId")
                        .HasName("PK_Addresses");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Addresses_City");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("City"), false);

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("IX_Addresses_CountryCode");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CountryCode"), false);

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Addresses_Region");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Region"), false);

                    b.HasIndex("ClientId", "AddressLine1", "AddressLine2", "AddressLine3", "AddressLine4", "City", "Region", "PostalCode", "CountryCode")
                        .IsUnique()
                        .HasDatabaseName("UX_ClientAddresses_Address")
                        .HasFilter("[AddressLine2] IS NOT NULL AND [AddressLine3] IS NOT NULL AND [AddressLine4] IS NOT NULL AND [Region] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClientId", "AddressLine1", "AddressLine2", "AddressLine3", "AddressLine4", "City", "Region", "PostalCode", "CountryCode"), false);

                    b.ToTable("ClientAddresses", "dbo");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.ClientEntity", b =>
                {
                    b.Property<long>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClientId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ClientId"), 1L, 1);

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Email")
                        .HasDefaultValueSql("NULL");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(56)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UtcCreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcCreatedDate");

                    b.Property<DateTime?>("UtcDeletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcDeletedDate")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime?>("UtcUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcUpdatedDate")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("ClientId")
                        .HasName("PK_Clients");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Client_Name");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Name"), false);

                    b.ToTable("Clients", "dbo");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.InvoiceEntity", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("InvoiceId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceId"), 1L, 1);

                    b.Property<long>("ClientId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ClientId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Description");

                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("Guid")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(8)")
                        .HasColumnName("Number");

                    b.Property<short>("PaymentTermDays")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("PaymentTermDays");

                    b.Property<short>("Status")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UtcCreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcCreatedDate");

                    b.Property<DateTime>("UtcDate")
                        .HasColumnType("DATE")
                        .HasColumnName("UtcDate");

                    b.Property<DateTime?>("UtcDeletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcDeletedDate")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime>("UtcDueDate")
                        .HasColumnType("DATE")
                        .HasColumnName("UtcDueDate");

                    b.Property<DateTime?>("UtcUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcUpdatedDate")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("InvoiceId")
                        .HasName("PK_Invoices");

                    b.HasIndex("UtcDate")
                        .HasDatabaseName("IX_Invoices_UtcDate");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("UtcDate"), false);

                    b.HasIndex("UtcDueDate")
                        .HasDatabaseName("IX_Invoices_UtcDueDate");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("UtcDueDate"), false);

                    b.HasIndex("ClientId", "Number")
                        .IsUnique()
                        .HasDatabaseName("UX_Invoices_ClientId_Number");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("ClientId", "Number"), false);

                    b.ToTable("Invoices", "dbo");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.InvoiceItemEntity", b =>
                {
                    b.Property<long>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BIGINT")
                        .HasColumnName("InvoiceItemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("InvoiceItemId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(128)")
                        .HasColumnName("Description");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("InvoiceId");

                    b.Property<decimal>("Price")
                        .HasPrecision(19, 4)
                        .HasColumnType("DECIMAL(19,4)")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT")
                        .HasColumnName("Quantity");

                    b.Property<DateTime>("UtcCreatedDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcCreatedDate");

                    b.Property<DateTime?>("UtcDeletedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcDeletedDate")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime?>("UtcUpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("UtcUpdatedDate")
                        .HasDefaultValueSql("NULL");

                    b.HasKey("InvoiceItemId")
                        .HasName("PK_InvoiceItem");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems", "dbo");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.ClientAddressEntity", b =>
                {
                    b.HasOne("Invoice.Api.Data.Entities.ClientEntity", "Client")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClientAddresses_Clients_ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("Invoice.Api.Data.Entities.ClientEntity", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Invoices_Clients_ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.InvoiceItemEntity", b =>
                {
                    b.HasOne("Invoice.Api.Data.Entities.InvoiceEntity", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItem_Invoice_InvoiceId");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.ClientEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoice.Api.Data.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
